### ISSUE TITLE
Question: How to add Flight Stabilizers

### ISSUE THREAD

**Issue by Lilothestitch16** [Jibinsu/BGE20th-save-editor#1]
Hi. How do I add Flight Stabilizers using the save editor? I'm trying to add one or more of them.

**Comment by Jibinsu** [comment]
Hey, so while the save editor is workable, there is still alot to figure out, the inventory management system being one of them, at this point i havent figured out how it works and if other things need to be edited along side it, once i figure it out ill release an update and ill also update the readme to be more clear on what is currently possible.

**Comment by Lilothestitch16** [comment]
ok thanks.
